/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getServerMetrics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getSession"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/diffs/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getCurrentDiff"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/diffs/{diffId}/files/{fileId}/patch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getFilePatch"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/diffs/{diffId}/files/{fileId}/contents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getFileContents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listComments"];
    put?: never;
    post: operations["createComment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/comments/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["importComments"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/comments/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["exportComments"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/comments/{commentId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteComment"];
    options?: never;
    head?: never;
    patch: operations["updateComment"];
    trace?: never;
  };
  "/api/v1/review-marks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listReviewMarks"];
    put?: never;
    post?: never;
    delete: operations["clearReviewMarks"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/review-marks/{fileId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["putReviewMark"];
    post?: never;
    delete: operations["deleteReviewMark"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ServerMetrics: {
      rssBytes: number;
      cpuUsage: number;
    };
    /** @enum {string} */
    DiffMode: "all" | "staged" | "unstaged";
    Session: {
      id: string;
      /** @enum {string} */
      source: "local" | "stdin";
      name: string;
      root: string;
      capabilities: {
        scopes: components["schemas"]["DiffMode"][];
        live: boolean;
        fullFileContents: boolean;
      };
    };
    ChangedFile: {
      id: string;
      path: string;
      oldPath: string | null;
      status: string;
      indexStatus: string;
      worktreeStatus: string;
      additions: number;
      deletions: number;
      binary: boolean;
      fingerprint: string;
      recreated?: boolean;
    };
    RepositoryDiff: {
      /** @enum {string} */
      source: "local" | "stdin";
      root: string;
      name: string;
      branch: string;
      head: string | null;
      mode: components["schemas"]["DiffMode"];
      files: components["schemas"]["ChangedFile"][];
      revision: string;
    };
    FilePatch: {
      patch: string;
      message: string | null;
      contents?: components["schemas"]["FileContents"];
    };
    FileContents: {
      before: string;
      after: string;
    };
    ReviewOrigin: {
      /** @enum {string} */
      source: "local" | "stdin";
      repository: string;
      branch: string;
      head: string | null;
      revision: string;
      file: {
        status: string;
        oldPath: string | null;
      };
    };
    ReviewComment: {
      id: string;
      path: string;
      scope: components["schemas"]["DiffMode"];
      fingerprint: string;
      /** @enum {string} */
      side: "additions" | "deletions";
      start: number;
      end: number;
      code: string;
      body: string;
      /** @enum {string} */
      status: "open" | "resolved";
      createdAt: number;
      origin?: components["schemas"]["ReviewOrigin"];
    };
    CreateComment: {
      diffId: string;
      fileId: string;
      scope: components["schemas"]["DiffMode"];
      fileVersion: string;
      /** @enum {string} */
      side: "additions" | "deletions";
      start: number;
      end: number;
      body: string;
    };
    UpdateComment: {
      body?: string;
      /** @enum {string} */
      status?: "open" | "resolved";
    };
    ReviewMark: {
      fileId: string;
      fileVersion: string;
      scope: components["schemas"]["DiffMode"];
    };
    Problem: {
      type: string;
      title: string;
      status: number;
      detail: string;
    };
  };
  responses: {
    /** @description Request failed. */
    Problem: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    Scope: components["schemas"]["DiffMode"];
    DiffId: string;
    FileId: string;
    FileVersion: string;
    CommentId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getServerMetrics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description CPU and resident memory used by the ServeDiff server process. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServerMetrics"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Active diff source and capabilities. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getCurrentDiff: {
    parameters: {
      query: {
        scope: components["parameters"]["Scope"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current diff snapshot. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepositoryDiff"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getFilePatch: {
    parameters: {
      query: {
        scope: components["parameters"]["Scope"];
        fileVersion: components["parameters"]["FileVersion"];
      };
      header?: never;
      path: {
        diffId: components["parameters"]["DiffId"];
        fileId: components["parameters"]["FileId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File patch. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FilePatch"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getFileContents: {
    parameters: {
      query: {
        scope: components["parameters"]["Scope"];
        fileVersion: components["parameters"]["FileVersion"];
      };
      header?: never;
      path: {
        diffId: components["parameters"]["DiffId"];
        fileId: components["parameters"]["FileId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Complete before and after contents. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FileContents"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listComments: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All comments for the active source. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            comments: components["schemas"]["ReviewComment"][];
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createComment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateComment"];
      };
    };
    responses: {
      /** @description Created comment. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewComment"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  importComments: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          comments: components["schemas"]["ReviewComment"][];
        };
      };
    };
    responses: {
      /** @description Idempotently imported comments. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            comments: components["schemas"]["ReviewComment"][];
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  exportComments: {
    parameters: {
      query?: {
        includeResolved?: boolean;
        revision?: string;
        scope?: components["schemas"]["DiffMode"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Canonical agent-ready export. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/xml": string;
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        commentId: components["parameters"]["CommentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Comment deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
  updateComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        commentId: components["parameters"]["CommentId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateComment"];
      };
    };
    responses: {
      /** @description Updated comment. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewComment"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listReviewMarks: {
    parameters: {
      query: {
        scope: components["parameters"]["Scope"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Reviewed file versions. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            marks: components["schemas"]["ReviewMark"][];
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  clearReviewMarks: {
    parameters: {
      query: {
        scope: components["parameters"]["Scope"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Scope review marks cleared. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
  putReviewMark: {
    parameters: {
      query: {
        scope: components["parameters"]["Scope"];
      };
      header?: never;
      path: {
        fileId: components["parameters"]["FileId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          fileVersion: string;
        };
      };
    };
    responses: {
      /** @description Stored review mark. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewMark"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteReviewMark: {
    parameters: {
      query: {
        scope: components["parameters"]["Scope"];
      };
      header?: never;
      path: {
        fileId: components["parameters"]["FileId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Review mark deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
}
