/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v2/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Check authenticated database readiness and ingestion compatibility. State identity changes when the account database is replaced. */
    get: operations["getIngestionHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/ingestion-jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Durably accept an immutable submission. Identical retries return the same job; changed payloads conflict. Acceptance is not publication. */
    post: operations["acceptIngestion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/ingestion-jobs/{jobId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Owner-scoped durable job status. Cancellation of a client does not cancel accepted work. */
    get: operations["getIngestionJob"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Server-sent ingestion notifications. Event data contains contextId; query the catalog for durable state after reconnecting. */
    get: operations["watchIngestions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/contexts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listContexts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/contexts/{contextId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    get: operations["getContext"];
    put?: never;
    post?: never;
    /** @description Permanently delete this context or snapshot, including all scopes, comments, review marks, and retained diff data. Repository files are unchanged. */
    delete: operations["deleteContext"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getServerMetricsV2"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/contexts/{contextId}/session": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    get: operations["getSessionV2"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/contexts/{contextId}/diffs/current": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    get: operations["getCurrentDiffV2"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/contexts/{contextId}/diffs/{diffId}/versions/{versionId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    get: operations["getDiffVersionV2"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/contexts/{contextId}/diffs/{diffId}/files/{fileId}/patch": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    get: operations["getFilePatchV2"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/contexts/{contextId}/diffs/{diffId}/files/{fileId}/contents": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    get: operations["getFileContentsV2"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/contexts/{contextId}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    get: operations["listCommentsV2"];
    put?: never;
    post: operations["createCommentV2"];
    delete: operations["deleteCommentsV2"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/contexts/{contextId}/comments/import": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["importCommentsV2"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/contexts/{contextId}/comments/export": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    get: operations["exportCommentsV2"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/contexts/{contextId}/comments/{commentId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteCommentV2"];
    options?: never;
    head?: never;
    patch: operations["updateCommentV2"];
    trace?: never;
  };
  "/api/v2/contexts/{contextId}/review/comments": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    get: operations["listAgentReviewCommentsV2"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/contexts/{contextId}/review/comments/{commentId}/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["resolveAgentReviewCommentV2"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/contexts/{contextId}/review-marks": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    get: operations["listReviewMarksV2"];
    put?: never;
    post?: never;
    delete: operations["clearReviewMarksV2"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/contexts/{contextId}/review-marks/{fileId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    get?: never;
    put: operations["putReviewMarkV2"];
    post?: never;
    delete: operations["deleteReviewMarkV2"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Comparison: {
      /** @enum {string} */
      kind: "working-tree" | "branch";
      /** @description Logical comparison baseline. HEAD for working changes; normalized Git ref for branch comparisons. */
      baseRef: string;
      /** @description Resolved baseline tip at collection time. Absent for unborn checkouts. */
      baseCommit?: string;
      /** @description Commit actually used as the branch comparison baseline. */
      mergeBase?: string;
    };
    AgentSession: {
      harness: string;
      id: string;
      name?: string;
    };
    SessionAssociation: {
      sourceId: string;
      harness: string;
      id: string;
      name?: string;
      /** Format: int64 */
      firstObservedAt: number;
      /** Format: int64 */
      lastObservedAt: number;
    };
    ObservationMetadata: {
      /** @description Producer-provided source identity, independent of hostname and path. */
      sourceId: string;
      hostname: string;
      runId: string;
      agent: string;
      trigger: string;
      repositoryKey: string;
      repositoryName: string;
      remoteUrl: string;
      checkoutKey: string;
      /** @description True for a linked Git worktree, false for the primary checkout. Omitted when unknown in older snapshots. */
      linkedWorktree?: boolean;
      /** @description Source-local path; the server does not access it. */
      root: string;
      worktreeName: string;
      branch: string;
      /** @description Stable producer branch identity, preserved through branch renames. Optional for older producers and detached HEAD. */
      branchId?: string;
      head: string | null;
      /**
       * Format: int64
       * @description Producer collection time in Unix milliseconds.
       */
      collectedAt: number;
      collectorVersion: string;
      comparison?: components["schemas"]["Comparison"];
      agentSession?: components["schemas"]["AgentSession"];
      /** @description Directory whose manual command or agent event triggered collection; does not establish authorship. */
      triggerRoot?: string;
    };
    IngestionScope: {
      snapshot: components["schemas"]["RepositoryDiff"];
      /** @description File previews keyed by snapshot file ID. */
      patches: {
        [key: string]: components["schemas"]["FilePatch"];
      };
    };
    IngestionJob: {
      id: string;
      submissionId: string;
      /** @enum {string} */
      state: "queued" | "running" | "retrying" | "succeeded" | "failed";
      attempt: number;
      contextId?: string;
      detail?: string;
    };
    IngestionRequest: {
      /**
       * @description Current producers send 2. Legacy version 1 remains accepted for ingestion and replay.
       * @enum {integer}
       */
      protocolVersion: 3;
      /** @description Retry identity. Reusing it with different content fails. */
      submissionId: string;
      /** @description Optional SHA256 of complete contents and staging state, independent of preview truncation and timestamps. Omit when complete identity cannot be proven. */
      contentHash?: string;
      metadata: components["schemas"]["ObservationMetadata"];
      scopes: components["schemas"]["IngestionScope"][];
    };
    ContextPage: {
      contexts: components["schemas"]["Context"][];
      nextCursor: string | null;
    };
    Context: {
      id: string;
      /** @enum {string} */
      kind: "observation";
      /**
       * @description Diff origin, independent of context kind and submission directory.
       * @enum {string}
       */
      source?: "local" | "stdin";
      name: string;
      /** @description Checked-out branch, or detached HEAD label. Null for captures or unknown metadata. */
      branch: string | null;
      /** @description Linked worktree directory name. Null for the main checkout or a capture. */
      worktreeName: string | null;
      root: string | null;
      locationId: string | null;
      repositoryId: string | null;
      /** Format: int64 */
      createdAt: number;
      /** Format: int64 */
      lastSubmittedAt: number;
      /**
       * Format: int64
       * @description Latest commit or working-tree change time in Unix milliseconds. Submission time for captures; zero when worktree change metadata is unknown.
       */
      lastChangedAt: number;
      /** @description Unique files with staged, unstaged, or untracked changes, independent of the selected scope. Captures use their snapshot file count. Null when change metadata is unknown. */
      changedFileCount: number | null;
      /** Format: int64 */
      expiresAt: number | null;
      submittedFrom: string | null;
      /** @enum {string} */
      availability: "unchecked" | "available" | "unavailable";
      /** @description A newer collection superseded this snapshot for the same owner, source, repository, checkout, branch, and comparison policy. Collection time determines freshness; arrival order breaks ties. Freshness survives snapshot expiry and pruning. False for ungrouped piped observations. */
      stale?: boolean;
      capabilities: components["schemas"]["Session"]["capabilities"];
      observation?: components["schemas"]["ObservationMetadata"];
      /** @description Sessions that observed this snapshot, including collections deduplicated into the same review. Names reflect latest supplied session metadata; no authorship is implied. */
      sessions?: components["schemas"]["SessionAssociation"][];
    };
    ServerMetrics: {
      rssBytes: number;
      cpuUsage: number;
    };
    /** @enum {string} */
    DiffMode: "all" | "staged" | "unstaged";
    /** @enum {string} */
    CapabilityState: "enabled" | "disabled" | "unavailable";
    Capability: {
      state: components["schemas"]["CapabilityState"];
    };
    ScopesCapability: {
      state: components["schemas"]["CapabilityState"];
      values: components["schemas"]["DiffMode"][];
    };
    Session: {
      id: string;
      user: components["schemas"]["User"];
      locationId: string | null;
      repositoryId: string | null;
      /** @enum {string} */
      source: "local" | "stdin";
      name: string;
      root: string;
      capabilities: {
        diff: {
          scopes: components["schemas"]["ScopesCapability"];
          refresh: components["schemas"]["Capability"];
          stagingMetadata: components["schemas"]["Capability"];
        };
        files: {
          contents: components["schemas"]["Capability"];
        };
        review: {
          comments: components["schemas"]["Capability"];
        };
      };
    };
    ChangedFile: {
      id: string;
      path: string;
      oldPath: string | null;
      status: string;
      indexStatus: string;
      worktreeStatus: string;
      additions: number;
      deletions: number;
      binary: boolean;
      fingerprint: string;
      recreated?: boolean;
    };
    RepositoryDiff: {
      id: string;
      versionId: string;
      locationId: string | null;
      repositoryId: string | null;
      /** @enum {string} */
      source: "local" | "stdin";
      root: string;
      name: string;
      branch: string;
      head: string | null;
      mode: components["schemas"]["DiffMode"];
      files: components["schemas"]["ChangedFile"][];
      revision: string;
    };
    FilePatch: {
      patch: string;
      message: string | null;
      contents?: components["schemas"]["FileContents"];
    };
    FileContents: {
      before: string;
      after: string;
    };
    ReviewOrigin: {
      diffId: string;
      versionId: string;
      /** @enum {string} */
      source: "local" | "stdin";
      repository: string;
      branch: string;
      head: string | null;
      revision: string;
      file: {
        status: string;
        oldPath: string | null;
      };
    };
    ReviewComment: {
      id: string;
      diffId: string;
      versionId: string;
      path: string;
      scope: components["schemas"]["DiffMode"];
      fingerprint: string;
      /**
       * @description Omitted means a line comment. File comments use additions, zero start/end, and empty code.
       * @enum {string}
       */
      target?: "file" | "lines";
      /** @enum {string} */
      side: "additions" | "deletions";
      start: number;
      end: number;
      code: string;
      body: string;
      /** @enum {string} */
      status: "open" | "resolved";
      createdAt: number;
      origin?: components["schemas"]["ReviewOrigin"];
    };
    AgentReviewComment: {
      id: string;
      diffId: string;
      versionId: string;
      path: string;
      scope: components["schemas"]["DiffMode"];
      fingerprint: string;
      /**
       * @description Omitted means a line comment. File comments use additions, zero start/end, and empty code.
       * @enum {string}
       */
      target?: "file" | "lines";
      /** @enum {string} */
      side: "additions" | "deletions";
      start: number;
      end: number;
      code: string;
      body: string;
      /** @enum {string} */
      status: "open" | "resolved";
      createdAt: number;
      origin?: components["schemas"]["ReviewOrigin"];
      /** @enum {string} */
      applicability: "anchored" | "stale" | "other-scope" | "unknown";
      actionable: boolean;
    };
    ResolveReviewComment: {
      comment_id: string;
      /** @enum {string} */
      status: "resolved";
    };
    CreateComment: {
      diffId: string;
      versionId: string;
      fileId: string;
      scope: components["schemas"]["DiffMode"];
      fileVersion: string;
      /**
       * @description Omitted means a line comment. File comments use additions and zero start/end.
       * @enum {string}
       */
      target?: "file" | "lines";
      /** @enum {string} */
      side: "additions" | "deletions";
      start: number;
      end: number;
      body: string;
    };
    UpdateComment: {
      body?: string;
      /** @enum {string} */
      status?: "open" | "resolved";
    };
    ReviewMark: {
      diffId: string;
      versionId: string;
      fileId: string;
      fileVersion: string;
      scope: components["schemas"]["DiffMode"];
    };
    User: {
      id: string;
      name: string;
    };
    Problem: {
      type: string;
      title: string;
      status: number;
      detail: string;
      code?: string;
      capability?: string;
    };
  };
  responses: {
    /** @description Request failed. */
    Problem: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    ContextId: string;
    Scope: components["schemas"]["DiffMode"];
    DiffId: string;
    VersionId: string;
    VersionIdPath: string;
    FileId: string;
    FileVersion: string;
    CommentId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getIngestionHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Database readiness and available HTTP ingestion capabilities. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            stateId: string;
            protocolVersion: number;
            /** @description Whether this runtime accepts HTTP ingestion. False for foreground local snapshots. */
            ingestionEnabled?: boolean;
            queuedIngestion?: boolean;
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  acceptIngestion: {
    parameters: {
      query?: never;
      header?: {
        "X-Servediff-State"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IngestionRequest"];
      };
    };
    responses: {
      /** @description Durable job accepted; poll its Location until succeeded or failed. */
      202: {
        headers: {
          Location?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngestionJob"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getIngestionJob: {
    parameters: {
      query?: never;
      header?: {
        "X-Servediff-State"?: string;
      };
      path: {
        jobId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current job status and committed context identity when successful. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngestionJob"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  watchIngestions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server-sent events named ingestion, with JSON data containing contextId. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": string;
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listContexts: {
    parameters: {
      query?: {
        /** @description Search observation metadata. */
        q?: string;
        repository?: string;
        branch?: string;
        worktree?: string;
        hostname?: string;
        sourceId?: string;
        runId?: string;
        harness?: string;
        sessionId?: string;
        sessionName?: string;
        limit?: number;
        cursor?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stored observations. Listing never accesses a checkout or runs Git. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContextPage"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getContext: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stable review target metadata and capabilities. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Context"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteContext: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Context and its review data deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components["responses"]["Problem"];
      default: components["responses"]["Problem"];
    };
  };
  getServerMetricsV2: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description CPU and resident memory used by the ServeDiff server process. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServerMetrics"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getSessionV2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Active diff source and capabilities. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getCurrentDiffV2: {
    parameters: {
      query: {
        scope: components["parameters"]["Scope"];
      };
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current diff snapshot. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepositoryDiff"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getDiffVersionV2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
        diffId: components["parameters"]["DiffId"];
        versionId: components["parameters"]["VersionIdPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Retained immutable diff version. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepositoryDiff"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getFilePatchV2: {
    parameters: {
      query: {
        versionId: components["parameters"]["VersionId"];
        scope: components["parameters"]["Scope"];
        fileVersion: components["parameters"]["FileVersion"];
      };
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
        diffId: components["parameters"]["DiffId"];
        fileId: components["parameters"]["FileId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File patch. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FilePatch"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getFileContentsV2: {
    parameters: {
      query: {
        versionId: components["parameters"]["VersionId"];
        scope: components["parameters"]["Scope"];
        fileVersion: components["parameters"]["FileVersion"];
      };
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
        diffId: components["parameters"]["DiffId"];
        fileId: components["parameters"]["FileId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Complete before and after contents. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FileContents"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listCommentsV2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All comments for the active source. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            comments: components["schemas"]["ReviewComment"][];
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createCommentV2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateComment"];
      };
    };
    responses: {
      /** @description Created comment. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewComment"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteCommentsV2: {
    parameters: {
      query: {
        status: "all" | "open" | "resolved" | "stale";
      };
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Remaining comments after bulk deletion. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            comments: components["schemas"]["ReviewComment"][];
            deleted: number;
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  importCommentsV2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          comments: components["schemas"]["ReviewComment"][];
        };
      };
    };
    responses: {
      /** @description Idempotently imported comments. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            comments: components["schemas"]["ReviewComment"][];
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  exportCommentsV2: {
    parameters: {
      query?: {
        includeResolved?: boolean;
        commentId?: string;
        revision?: string;
        scope?: components["schemas"]["DiffMode"];
      };
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Canonical agent-ready export. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/xml": string;
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteCommentV2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
        commentId: components["parameters"]["CommentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Comment deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
  updateCommentV2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
        commentId: components["parameters"]["CommentId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateComment"];
      };
    };
    responses: {
      /** @description Updated comment. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewComment"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listAgentReviewCommentsV2: {
    parameters: {
      query?: {
        includeResolved?: boolean;
      };
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Agent-ready comments with current applicability. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            comments: components["schemas"]["AgentReviewComment"][];
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  resolveAgentReviewCommentV2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
        commentId: components["parameters"]["CommentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Idempotently resolved comment. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResolveReviewComment"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listReviewMarksV2: {
    parameters: {
      query: {
        scope: components["parameters"]["Scope"];
      };
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Reviewed file versions. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            marks: components["schemas"]["ReviewMark"][];
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  clearReviewMarksV2: {
    parameters: {
      query: {
        scope: components["parameters"]["Scope"];
      };
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Scope review marks cleared. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
  putReviewMarkV2: {
    parameters: {
      query: {
        scope: components["parameters"]["Scope"];
      };
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
        fileId: components["parameters"]["FileId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          fileVersion: string;
          versionId: string;
        };
      };
    };
    responses: {
      /** @description Stored review mark. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewMark"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteReviewMarkV2: {
    parameters: {
      query: {
        scope: components["parameters"]["Scope"];
      };
      header?: never;
      path: {
        contextId: components["parameters"]["ContextId"];
        fileId: components["parameters"]["FileId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Review mark deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
}
